package:
  name: pyladies_conda       # lower case name of package, may contain '-' but no spaces
  version: "0.0.1"    # version of package. Should use the PEP-386 verlib
                      # conventions. Note that YAML will interpret
                      # versions like 1.0 as floats, meaning that 1.0 will
                      # be the same as 1. To avoid this, always put the
                      # version in quotes, so that it will be interpreted
                      # as a string.

                      # The version cannot contain a dash '-' character.

source:
  # The source section specifies where the source code of the package is
  # coming from
  
  # git:
  # git_url can also be a relative path to the recipe directory
  git_url: https://github.com/apanda4/Practice.git
  git_tag: 0.0.1

  # or from a local path:
  # if the path is relative it is taken relative to the recipe
  # directory. The source is copied to the work directory before building.
  #path: ../src

  #########################################################################
  # Note, the source section is optional. If you want to specify a source #
  # location locally, the easiest way is to not specify the source here,  #
  # but to just add something like                                        #
  #                                                                       #
  # cp -r $RECIPE_DIR/../src .                                            #
  # cd src                                                                #
  # ...                                                                   #
  #                                                                       #
  # in build.sh (and similarly in bld.bat). This assumes the source is    #
  # shipped alongside the recipe in src.                                  #
  #########################################################################

requirements:
  build:
    - python
    - setuptools
	- vJinja2==2.7.3
	- MarkupSafe==0.23
	- backports.ssl-match-hostname==3.4.0.2
	- certifi==14.5.14
	- gnureadline==6.3.3
	- ipython==2.3.1
	- matplotlib==1.4.2
	- mock==1.0.1
	- nose==1.3.4
	- numpy==1.9.1
	- Cython==0.21.2
	- pyparsing==2.0.3
	- python-dateutil==2.4.0
	- pytz==2014.10
	- pyzmq==14.5.0
	- six==1.9.0
	- tornado==4.0.2
	- wsgiref==0.1.2

  run:
    - python

test:
  imports:
    - pyladies_conda

about:
  home: https://github.com/apanda4/Practice
  license: BSD
  summary: "trying to make a new environment"